@startuml flowchart
メニュー: ゲームモード選択または設定へ移動できる
設定: ボタン配置など各種設定値の変更
ゲーム: 遊ぶところ

state ゲーム {
  [*] -> ゲームプレイ
  ゲームプレイ -> ポーズメニュー
  ゲームプレイ -> [*]
  ポーズメニュー -> ゲームプレイ
  ポーズメニュー -> [*]
}

[*] -> メニュー
メニュー -> 設定
設定 -> メニュー
メニュー -> ゲーム
ゲーム -> メニュー
@enduml
